### ISSUE TITLE
This is a request.

### ISSUE THREAD

**Issue by amitadlak** [aayushmnit/AV-Hackathon-3.X#1]
Hi Aayush,
I am new to this GitHub and analytics Vidhya Hackathons, so I am not sure how to get in touch with you so writing it here.
Would it be possible for you to provide the Data Set and problem statement for which you have given the code here.
Because data sets and problem statements will be active until Hackathon is active, I am in learning phase.
Any help would be appreciated.
Thank you.

Regards,
Amit Adlak
amitadlak@gmail.com

**Comment by aayushmnit** [comment]
Hi Amitadlak,

Actually Data sharing after the hackathon is not allowed by Analytics vidhya. What you can do is register in their latest Hackathon and then see winners approaches after the competition.

Hope this helps.

Regards,
Aayush

**Comment by amitadlak** [comment]
@aayushmnit Thank you for your reply.

Yes I did register in Date your Data and now I will wait for winners to reveal their approch.

Regards,
Amit Adlak
